# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ocr.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tocr.proto\x12\x03ocr\"\x1f\n\x0cPingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\r\n\x0bPingRequest\"#\n\x12UploadImageRequest\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\"&\n\x13UploadImageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2v\n\x03OCR\x12+\n\x04Ping\x12\x10.ocr.PingRequest\x1a\x11.ocr.PingResponse\x12\x42\n\x0bUploadImage\x12\x17.ocr.UploadImageRequest\x1a\x18.ocr.UploadImageResponse(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ocr_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PINGRESPONSE._serialized_start=18
  _PINGRESPONSE._serialized_end=49
  _PINGREQUEST._serialized_start=51
  _PINGREQUEST._serialized_end=64
  _UPLOADIMAGEREQUEST._serialized_start=66
  _UPLOADIMAGEREQUEST._serialized_end=101
  _UPLOADIMAGERESPONSE._serialized_start=103
  _UPLOADIMAGERESPONSE._serialized_end=141
  _OCR._serialized_start=143
  _OCR._serialized_end=261
# @@protoc_insertion_point(module_scope)
